sudo: required
services:
- docker
before_install:
- git clone --recursive https://github.com/aaronsewall/DualBootPatcher -b master DualBootPatcher/
- docker pull silverx2222/dualbootpatcher:9.3.0-14-base
- docker pull silverx2222/dualbootpatcher:9.3.0-14-android
- docker pull silverx2222/dualbootpatcher:9.3.0-14-linux
script:
- mkdir $HOME/.android
- mkdir -p ${TRAVIS_BUILD_DIR}/DualBootPatcher/builder/ && cd ${TRAVIS_BUILD_DIR}/DualBootPatcher/
- |
  docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/builder/DualBootPatcher:rw,z" -v "${HOME}/.android:/builder/.android:rw,z" silverx2222/dualbootpatcher:9.3.0-14-android bash << EOF
  cd DualBootPatcher/builder && cmake .. -DMBP_BUILD_TARGET=android -DMBP_BUILD_TYPE=debug && make -j16 && rm -rf assets && cpack && make apk -j16
  make android-system_armeabi-v7a -j16 && make -C data/devices -j16
  exit
  EOF
after_success:
- export TRAVIS_CURRENT_DATE=$(date +"%d%m%y-%Hh%Mm")
- ls -l ${TRAVIS_BUILD_DIR}/DualBootPatcher/Android_GUI/build/outputs/apk/debug/Android_GUI-debug.apk
- md5sum ${TRAVIS_BUILD_DIR}/DualBootPatcher/Android_GUI/build/outputs/apk/debug/Android_GUI-debug.apk
- cd ${TRAVIS_BUILD_DIR}/DualBootPatcher/Android_GUI/build/outputs/apk/debug/
- curl --upload-file ./Android_GUI-debug.apk https://transfer.sh/Android_GUI-debug-${TRAVIS_CURRENT_DATE}.apk
  > response
- cat response
deploy:
  provider: releases
  api_key:
    secure: gRZrA5w61QTnUf6j34Mirxn3hSrrO7WZYzmW25zwy/zDBNYx0TS6mMgpbBhluef6VQF35Ne2s5prbKiOEqAkELEGxzjzs2cLSapwODdNTzQ3IS15foDhmy9bN58rJCkzZeKIc4HavHVXkEPls6K37EIlPnp8ChOuCowbY51ENwgD8GhW1q9qpd5lA3pPfRzHbRV1PzkhKlGoJgLtlSRtDW27HO9Gs3lbqCrc1n+drHxr4dZMkOW/xdGYYBw3CT4LgSy03R0bCHA/jXm7T76HU5V/NGRjftkH7DNTTc8o2OwC+BUfOC+6ldY4o674ti2x2noQ8UsC8La1MHhS78CtB51ElfCBJlNXIsSyFDqk3eGG8npgKz8fWYiE4a4YhjvMhW97D2cxZsV7jW5nfgNvbzCWDsKPc1CoU/34uEwoy6xt92l45OYb40I6WBPmB7GME+S0CPJLt+YOFP5/HZirgnugaGHTb5OC3pvLglCUtcl2uTunk9E10yyF+E0lwj+oAej7LEc2ZAL+SKBYs1xEQGX5IKIh0j8/C/LhVFpfvOC+oNf9phzJqQrCibsQPnY7uYxBk1cg4FYUp02kuvaoL/lUEz1hbmFGEi/LCbkCbfuwOw8kiRIhM9su2e56z36jFA+cfywm4EMYRWDVqm4Hj9+VHteBfrETfsqL3FMZ8wE=
  file: "${TRAVIS_BUILD_DIR}/DualBootPatcher/Android_GUI/build/outputs/apk/debug/Android_GUI-debug.apk"
  on:
    repo: aaronsewall/DualBootPatcher
