sudo: required
services:
- docker
before_install:
- git clone --recursive https://github.com/aaronsewall/DualBootPatcher -b master DualBootPatcher/
- docker pull silverx2222/dualbootpatcher:9.3.0-14-base
- docker pull silverx2222/dualbootpatcher:9.3.0-14-android
- docker pull silverx2222/dualbootpatcher:9.3.0-14-linux
script:
- mkdir $HOME/.android
- mkdir -p ${TRAVIS_BUILD_DIR}/DualBootPatcher/builder/ && cd ${TRAVIS_BUILD_DIR}/DualBootPatcher/
- |
  docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/builder/DualBootPatcher:rw,z" -v "${HOME}/.android:/builder/.android:rw,z" silverx2222/dualbootpatcher:9.3.0-14-android bash << EOF
  cd DualBootPatcher/builder && cmake .. -DMBP_BUILD_TARGET=android -DMBP_BUILD_TYPE=debug && make -j16 && rm -rf assets && cpack && make apk -j16
  make android-system_armeabi-v7a -j16 && make -C data/devices -j16
  exit
  EOF
after_success:
- export TRAVIS_CURRENT_DATE=$(date +"%d%m%y-%Hh%Mm")
- ls -l ${TRAVIS_BUILD_DIR}/DualBootPatcher/Android_GUI/build/outputs/apk/debug/Android_GUI-debug.apk
- md5sum ${TRAVIS_BUILD_DIR}/DualBootPatcher/Android_GUI/build/outputs/apk/debug/Android_GUI-debug.apk
- cd ${TRAVIS_BUILD_DIR}/DualBootPatcher/Android_GUI/build/outputs/apk/debug/
- curl --upload-file ./Android_GUI-debug.apk https://transfer.sh/Android_GUI-debug-${TRAVIS_CURRENT_DATE}.apk
  > response
- cat response
deploy:
  provider: releases
  api_key:
    secure: 6V/10hA5qF8Gy29Ihn9xmyACIzGp7AVLZR8SMGkZy1vX+wOR/ByvS7UtITNuSG/bw7ANHAIQvtD0bEWTsP1zZPGKtMm9TQt+SJYQNH+DtWW1egqkJNnEkBXfZWVLp021iBMBXpHxemnIp6Q1+wJFyYsQ13148wkNIQF3stG6CKi1plBPGTHztgEm9L4BipaBlTLsD0jm+/XaYBM6OsQJ0x9a+Xc6kSdlzZZRf6bbbuVvyjr8HIP0O+p24MhM/Y6WRW+7y2CS35x0YKjWeVfFwt6pKRvoA8r8+TB7TX5aZrzuLwtXfdH50JduNoiLfOQDrc/+RwiekdGgbh5L6NPH3iWTogP2pPtS0AUpJOLLkVbQBAOuTh0dlKnxyQGijwxqtpJsoA1yGWxYSV8fK9T/ZBvbJ8CWSwVBlzbcd+MKDEDcZESsuMHRBsF5x02kro50aT3iHg4bjMyf0FmA9qh3zJWDfw8M8v79RZoZFMXtGM/M9xxad8kJe0pKrjHP5UtWFB2bhf4tb1Ga0zvVg1rnGHIpxSPt5QzOidGGNPDXsQ+DT2JabPv8qOIASaSAV8exv8peFtdaLTxBkphomqWCYQeFNkcdAr1vMwp0jwn8I0dflZqPVqtxnzLOBXgBr4wxKBETyembyqvz37SpNgtVJRnNgWuOnUE2vsa/hsF4+WQ=
  file: "${TRAVIS_BUILD_DIR}/Android_GUI/build/outputs/apk/debug/Android_GUI-debug.apk"
  on:
    repo: aaronsewall/DualBootPatcher
